Document: zelda-roth-se
Title: Debian zelda-roth-se Manual
Author: <insert document author here>
Abstract: This manual describes what zelda-roth-se is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zelda-roth-se/zelda-roth-se.sgml.gz

Format: postscript
Files: /usr/share/doc/zelda-roth-se/zelda-roth-se.ps.gz

Format: text
Files: /usr/share/doc/zelda-roth-se/zelda-roth-se.text.gz

Format: HTML
Index: /usr/share/doc/zelda-roth-se/html/index.html
Files: /usr/share/doc/zelda-roth-se/html/*.html
