Document: zsdx
Title: Debian zsdx Manual
Author: <insert document author here>
Abstract: This manual describes what zsdx is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zsdx/zsdx.sgml.gz

Format: postscript
Files: /usr/share/doc/zsdx/zsdx.ps.gz

Format: text
Files: /usr/share/doc/zsdx/zsdx.text.gz

Format: HTML
Index: /usr/share/doc/zsdx/html/index.html
Files: /usr/share/doc/zsdx/html/*.html
