Document: zbom
Title: Debian zbom Manual
Author: <insert document author here>
Abstract: This manual describes what zbom is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zbom/zbom.sgml.gz

Format: postscript
Files: /usr/share/doc/zbom/zbom.ps.gz

Format: text
Files: /usr/share/doc/zbom/zbom.text.gz

Format: HTML
Index: /usr/share/doc/zbom/html/index.html
Files: /usr/share/doc/zbom/html/*.html
