Document: zsxd
Title: Debian zsxd Manual
Author: <insert document author here>
Abstract: This manual describes what zsxd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zsxd/zsxd.sgml.gz

Format: postscript
Files: /usr/share/doc/zsxd/zsxd.ps.gz

Format: text
Files: /usr/share/doc/zsxd/zsxd.text.gz

Format: HTML
Index: /usr/share/doc/zsxd/html/index.html
Files: /usr/share/doc/zsxd/html/*.html
