.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2016 Nathan Moore <natedevv@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SOLARUS-QUEST-EDITOR "6" "July 19, 2016" "solarus-quest-editor-1.5.0" "Games"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
solarus-quest-editor \- manual page for solarus-quest-editor 1.5.0
.SH SYNOPSIS
.B solarus-quest-editor
.RI [ options ] " files" ...
.br
.B bar
.RI [ options ] " files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B solarus-quest-editor.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBsolarus-quest-editor\fP is a program that allows one to develop quests for the solarus engine.
.br
.SH SEE ALSO
.BR solarus (6),
.BR solarus-run (6).
