Document: tunics
Title: Debian tunics Manual
Author: <insert document author here>
Abstract: This manual describes what tunics is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tunics/tunics.sgml.gz

Format: postscript
Files: /usr/share/doc/tunics/tunics.ps.gz

Format: text
Files: /usr/share/doc/tunics/tunics.text.gz

Format: HTML
Index: /usr/share/doc/tunics/html/index.html
Files: /usr/share/doc/tunics/html/*.html
